#!/bin/bash

set -e

MAIL_LOCATION='/var/mail'

_log() {
    local logfile=/var/log/mail.log
    if [ ! -f $logfile ]; then
        touch $logfile
        chown syslog:adm $logfile
        chmod 640 $logfile
    fi
    echo "$(date '+%b %e %H:%I:%S') $(hostname) entrypoint[$$]: $1" >> $logfile
}

_stop() {
    /etc/init.d/rsyslog stop
    if [ -f /var/run/dovecot/master.pid ]; then
        kill -15 $(cat /var/run/dovecot/master.pid)
        rm -rf /var/run/dovecot/master.pid
    fi
    _log "Docker entrypoint stop"
}

_create_account() {
    local login=$1
    local pass=$2
    local user=$(echo ${login} | cut -d @ -f1)
    local domain=$(echo ${login} | cut -d @ -f2)

    local uid=$(cat /etc/passwd | grep $MAIL_FS_USER | cut -d':' -f3)
    local gid=$(cat /etc/passwd | grep $MAIL_FS_USER | cut -d':' -f4)

    echo "${login}:{PLAIN}${pass}:${uid}:${gid}::${MAIL_FS_HOME}/${domain}/${user}::" > /etc/dovecot/userdb

    if [ ! -d "${MAIL_LOCATION}/${domain}" ]; then
        mkdir -p "${MAIL_LOCATION}/${domain}"
        chown ${uid}:${gid} "${MAIL_LOCATION}/${domain}"
    fi

    if [ ! -d "${MAIL_LOCATION}/${domain}/${user}" ]; then
        maildirmake.dovecot "${MAIL_LOCATION}/${domain}/${user}"
        maildirmake.dovecot "${MAIL_LOCATION}/${domain}/${user}/.Sent"
        maildirmake.dovecot "${MAIL_LOCATION}/${domain}/${user}/.Trash"
        maildirmake.dovecot "${MAIL_LOCATION}/${domain}/${user}/.Drafts"
        echo -e "INBOX\nSent\nTrash\nDrafts" >> "${MAIL_LOCATION}/${domain}/${user}/subscriptions"
        touch "${MAIL_LOCATION}/${domain}/${user}/.Sent/maildirfolder"
        chown -R ${uid}:${gid} "${MAIL_LOCATION}/${domain}/${user}"
    fi
}

trap "_stop" SIGINT SIGTERM SIGHUP

_log "Docker entrypoint start"

_create_account $MAIL_ADDRESS $MAIL_PASS

_log "Docker entrypoint configured"

# Start syslog daemon
/etc/init.d/rsyslog start

# Start Dovecot daemon
rm -rf /var/run/dovecot/master.pid
/usr/sbin/dovecot -c /etc/dovecot/dovecot.conf

$@ & wait ${!}
